name: Testing

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    testing:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Cache Composer
              id: cache-composer
              uses: actions/cache@v3
              with:
                path: vendor
                key: ${{ hashFiles('composer.lock') }}
            - name: Cache NPM
              id: cache-npm
              uses: actions/cache@v3
              with:
                path: node_modules
                key: ${{ hashFiles('package-lock.json') }}
            - name: Composer Install
              run: composer install
            - name: Hoist Sail!
              run: composer sail-up
            - name: Install
              run: |
                cp .env.example .env
                ./vendor/bin/sail npm install
                ./vendor/bin/sail npm run build
                ./vendor/bin/sail artisan migrate:fresh
            - name: PHP Style
              run: ./vendor/bin/sail composer pint
              if: always()
            - name: Test
              run: ./vendor/bin/sail artisan test --parallel --coverage
              if: always()
